language: node_js
node_js:
- 8.11.1
branches:
  only:
  - master
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install pyyaml
  - pip3 install pyyaml
  - python3 nav.py
install:
  - npm install
script: npm run build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run coveralls
