language: node_js
node_js:
  - 8.11.1
env:
  - URL="https://kakise.me" REPOSITORY_URL"git@github:Kakise/Blog" CONTEXT="deploy-preview" PULL_REQUEST="false"
branches:
  only:
  - master
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install
script: ./build.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run coveralls
