title: Le Blog de Kakise
subtitle: Le blog d'un codeur fou !
description: >-
  Salut et bienvenue sur mon blog ! Ici vous retrouverez mes projets, et autres
  réflexions tout à fait folles !
keywords: 'Blog, code, info, science'
author: Kakise
language: fr
timezone: Europe/Paris
social_links:
  github: 'https://github.com/Kakise'
  mail: mail@kakise.me
  twitter: 'https://twitter.com/Kakise_'
url: 'https://kakise.me'
pwa:
  manifest:
    body:
      background_color: '#E2E0DE'
      name: Le Blog de Kakise
      short_name: LBDK
      start_url: 'https://kakise.me'
      theme_color: '#E2E0DE'
