title: Le Blog de Kakise 
subtitle: Le blog d'un codeur fou !
description: Salut et bienvenue sur mon blog ! Ici vous retrouverez mes projets, et autres réflexions tout à fait folles !
keywords: Blog, code, info, science
author: Kakise
language: fr
timezone: Europe/Paris
social_links:
  github: https://github.com/Kakise 
  twitter: https://twitter.com/Kakise_
  mail: me@kakise.xyz 
url: https://kakise.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - admin/config.yml
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
index_generator:
  path: ''
  per_page: 5
  order_by: -date
default_category: uncategorized
category_map:
tag_map:
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: cactus
theme_config:
  colorscheme: light
deploy: 
  type: onesignal
  app_id: ONESIGNAL_APP_KEY
  app_auth_key: ONESIGNAL_APP_AUTH_KEY
  app_template_file: ./notif-tpl.json
sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml
pwa:
  manifest:
    path: /manifest.json
    body:
      name: Le Blog de Kakise
      short_name: LBDK
      icons:
        - src: /images/PWA_Cover.png
          sizes: 512x512
          type: image/png
      display: standalone
      theme_color: "#E2E0DE"
      background_color: "#E2E0DE"
      start_url: https://kakise.me
      gcm_sender_id: "482941778795"
      gcm_sender_id_comment: "Do not change the GCM Sender ID"
  serviceWorker:
    path: /sw.js
    preload:
      urls: URL_PLACEHOLDER
      posts: 10
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: "!!js/regexp /.*\\.(js|css|jpg|jpeg|png|gif)$/"
        strategy: cacheFirst
      - pattern: "!!js/regexp /\\//"
        strategy: networkFirst
  priority: 5
criticalcss:
  enable: true
  critical:
    minify: true
  htmlTagToReplace: "</\\s*head>"
  perPageCss: false
  priority: 4
  replacementHtmlHeader: "<style type=\"text/css\">"
  replacementHtmlTrailer: "</style></head>"
lazyload:
  enable: true 
  onlypost: true
  loadingImg:
feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
asciinema:
  enable: true
nofollow:
  enable: true
  exclude: