title: 'Blog, Photos et Histoires'
subtitle: 'Mon blog, écrits sur la vie d''un humain normal.'
description: >-
  Bienvenue dans mon blog, ici je poste mes travaux photos, mes histoires et un
  peu de tout sur ma vie.
keywords: 'code, informatique, science, photos, blog, podcast, news'
author: Kakise
language: fr
timezone: Europe/Paris
url: SITEURL
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: ' '
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
code_dir: downloads/code
i18n_dir: ':lang'
skip_render:
  - admin/config.yml
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
background:
  enable: false
  path: /images/bg.jpg
index_generator:
  order_by: '-date'
  path: ''
  per_page: 5
default_category: uncategorized
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: default
theme_config:
  colorscheme: dark
sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml
pwa:
  manifest:
    body:
      background_color: '#E2E0DE'
      display: standalone
      icons:
        - sizes: 512x512
          src: /images/PWA_Cover.png
          type: image/png
      name: Le Blog de Kakise
      short_name: LBDK
      start_url: /
      theme_color: '#E2E0DE'
    path: /manifest.json
  priority: 5
  serviceWorker:
    opts:
      networkTimeoutSeconds: 5
    path: /sw.js
    preload:
      posts: 10
      urls:
        - URL_PLACEHOLDER
    routes:
      - pattern: '!!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/'
        strategy: cacheFirst
      - pattern: '!!js/regexp /\//'
        strategy: cacheFirst
criticalcss:
  critical:
    minify: true
  enable: true
  htmlTagToReplace: </\s*head>
  perPageCss: false
  priority: 4
  replacementHtmlHeader: <style type="text/css">
  replacementHtmlTrailer: </style></head>
lazyload:
  enable: true
  loadingImg: /images/loading.gif
  onlypost: true
feed:
  content_limit: 140
  content_limit_delim: ' [...]'
  limit: true
  path: atom.xml
  type: atom
asciinema:
  enable: true
nofollow:
  enable: true
  exclude: yy
