# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Le Blog de Kakise 
subtitle: Le blog d'un codeur fou !
description: Salut et bienvenue sur mon blog ! Ici vous retrouverez mes projets, et autres réflexions tout à fait folles !
keywords: Blog, code, info, science
author: Kakise
language: fr
timezone: Europe/Paris
social_links:
  github: https://github.com/Kakise 
  twitter: https://twitter.com/Kakise_
  mail: me@kakise.xyz 
  
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://kakise.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - admin/config.yml
ignore:
  - scripts/**


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

theme_config:
  colorscheme: light

# Deploy:
deploy: 
  type: onesignal
  app_id: ONESIGNAL_APP_KEY
  app_auth_key: ZjllNTA3MTItMzhiZS00NDg4LTk5MDItYjczYmI2YjhlNTli
  app_template_file: ./notif-tpl.json
  
sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml

# PWA
pwa:
  manifest:
    path: /manifest.json
    body:
      name: Le Blog de Kakise
      short_name: LBDK
      icons:
        - src: /images/LBDK Cover.png
          sizes: 512x512
          type: image/png
      display: standalone
      theme_color: "#E2E0DE"
      background_color: "#E2E0DE"
      start_url: https://kakise.me
      gcm_sender_id: 482941778795
      gcm_sender_id_comment: "Do not change the GCM Sender ID"
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
        - /about/
        - /projets/
        - /archives/
      posts: 10
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: "!!js/regexp /.*\\.(js|css|jpg|jpeg|png|gif)$/"
        strategy: cacheFirst
      - pattern: "!!js/regexp /\\//"
        strategy: networkFirst
  priority: 5

# Critical CSS extractor
criticalcss:
  enable: true
  critical:
    minify: true
  htmlTagToReplace: "</\\s*head>"
  perPageCss: false
  priority: 4
  replacementHtmlHeader: "<style type=\"text/css\">"
  replacementHtmlTrailer: "</style></head>"

# Uncss
uncss:
  enable: true
  ignore: "#added_at_runtime"
  media: ["(min-width: 700px) handheld and (orientation: landscape)"]
  priority: 100
  timeout: 1000

lazyload:
  enable: true 
  onlypost: true
  loadingImg: # "./images/loading.gif" # Image found here: https://gfycat.com/fr/gifs/detail/SkinnySeveralAsianlion
  
feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

asciinema:
  enable: true

nofollow:
	enable: true
	exclude:
