title: Le Blog de Kakise
subtitle: Le blog d'un codeur fou !
description: >-
  Salut et bienvenue sur mon blog ! Ici vous retrouverez mes projets, et autres
  réflexions tout à fait folles !
keywords: 'Blog, code, info, science'
author: Kakise
language: fr
timezone: Europe/Paris
url: SITEURL
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: ' '
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
code_dir: downloads/code
i18n_dir: ':lang'
skip_render:
  - admin/config.yml
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
index_generator:
  order_by: '-date'
  path: ''
  per_page: 5
default_category: uncategorized
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: cactus
theme_config:
  colorscheme: light
deploy:
  app_auth_key: ONESIGNAL_APP_AUTH_KEY
  app_id: ONESIGNAL_APP_KEY
  app_template_file: ./notif-tpl.json
  type: onesignal
sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml
pwa:
  manifest:
    body:
      background_color: '#E2E0DE'
      display: standalone
      gcm_sender_id: '482941778795'
      icons:
        - sizes: 512x512
          src: /images/PWA_Cover.png
          type: image/png
      name: Le Blog de Kakise
      short_name: LBDK
      start_url: 'https://kakise.me'
      theme_color: '#E2E0DE'
    path: /manifest.json
  priority: 5
  serviceWorker:
    opts:
      networkTimeoutSeconds: 5
    path: /sw.js
    preload:
      posts: 10
      urls: URL_PLACEHOLDER
    routes:
      - pattern: '!!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/'
        strategy: cacheFirst
      - pattern: '!!js/regexp /\//'
        strategy: networkFirst
criticalcss:
  critical:
    minify: true
  enable: true
  htmlTagToReplace: </\s*head>
  perPageCss: false
  priority: 4
  replacementHtmlHeader: <style type="text/css">
  replacementHtmlTrailer: </style></head>
lazyload:
  enable: true
  onlypost: true
feed:
  content_limit: 140
  content_limit_delim: ' [...]'
  limit: true
  path: atom.xml
  type: atom
asciinema:
  enable: true
nofollow:
  enable: true
