backend:
  name: git-gateway
  repo: REPO_PLACEHOLDER
  branch: master
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

display_url: SITEURL_PLACEHOLDER

publish_mode: editorial_workflow

media_folder: "source/images"
public_folder: "images"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "source/_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default: "Untitled"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string", default: "Author"}
      - label: Gallery
        name: photos
        widget: list
        field: {label: Image, name: image, widget: image}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  - label: "Pages"
    name: "pages"
    label_singular: "Page"
    folder: "source/"
    filter: {field: "layout", value: "page"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default: "Untitled"}
      - label: Gallery
        name: photos
        widget: list
        field: {label: Photo, name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}