backend:
  name: github
  repo: Kakise/Blog
  branch: master
publish_mode: editorial_workflow
media_folder: "source/images"
public_folder: "images"
collections:
  - name: "posts"
    label: "Post"
    folder: "source/_posts"
    sort: "date:desc"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default: "Untitled"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Author"}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  - label: "Pages"
    name: "pages"
    folder: "source/"
    filter: {field: "layout", value: "page"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default: "Untitled"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  - label: "Misc"  
    name: "misc"
    editor:
      preview: false
    files:
    - name: "projects"
      label: "Projects"
      file: "source/_data/projects.json"
      fields:
        - label: "Project"
          name: "prj"
          widget: "list"
          fields:
          - {label: "Name", name: name, widget: string}
          - {label: "Url", name: url, widget: string}
          - {label: "Description", name: desc, widget: string}
    - name: "navigation"
      label: "Menu"
      file: "source/_data/nav.json"
      fields:
        - label: "Top Menu"
          name: "nav"
          widget: "list"
          fields:
          - {label: "Link Name", name: link, widget: string}
          - {label: "Url", name: url, widget: string}
    - name: "general"
      label: "General Configuration"
      file: "_config.yml"
      fields:
        - {label: "Title", name: title, widget: string}
        - {label: "Subtitle", name: subtitle, widget: string}
        - {label: "Description", name: description, widget: string}
        - {label: "Keywords", name: keywords, widget: string}
        - {label: "Author", name: author, widget: string}
        - {label: "Language", name: language, widget: string}
        - {label: "Timezone", name: timezone, widget: string}
        - label: "Social Links"
          name: social_links
          widget: list
          fields:
            - {label: "Github", name: github, widget: string}
            - {label: "Twitter", name: twitter, widget: string}
            - {label: "E-Mail", name: mail, widget: string}
        - {label: "Url", name: subtitle, widget: string}
        - label: "Progressive Web App"
          name: pwa
          widget: list
          fields:
            - label: "Manifest"
              name: manifest
              widget: list
              fields:
              - label: "Body"
                name: body
                wiget: list
                fields:
                - {label: "Name", name: name, widget: string}
                - {label: "Short Name", name: short_name, widget: string}
                - {label: "Theme Color", name: theme_color, widget: string}
                - {label: "Background Color", name: background_color, widget: string}
                - {label: "Start Url", name: start_url, widget: string}