backend:
  name: github
  repo: Kakise/Blog
  branch: master
publish_mode: editorial_workflow
media_folder: "source/images"
public_folder: "images"
collections:
  - name: "posts"
    label: "Post"
    folder: "source/_posts"
    sort: "date:desc"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default: "Untitled"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Author"}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  - label: "Pages"
    name: "pages"
    files:
    - name: "projects"
      label: "Projects"
      file: "source/_data/projects.json"
      widget: "list"
      fields:
        - {label: "Name", name: name, widget: string}
        - {label: "Url", name: url, widget: string}
        - {label: "Description", name: desc, widget: string}
