backend:
  name: github
  repo: Kakise/Blog
  branch: master
publish_mode: editorial_workflow
media_folder: "source/images"
public_folder: "source"
collections:
  - name: "posts"
    label: "Post"
    folder: "source/_posts"
    sort: "date:desc"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
