projects_url: https://github.com/Kakise

nav: NAV_PLACEHOLDER

social_links: SOC_PLACEHOLDER

logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false

favicon: 
  desktop:
    url: /images/favicon.ico
    gravatar: false
  android:
    url: /images/android-icon-192x192.png
    gravatar: false
  apple:
    url: /images/apple-icon.png
    gravatar: false

highlight: rainbow

page_width: 48


rss: atom.xml

open_graph: 
  fb_app_id:
  fb_admins:
  twitter_id: Kakise_
  google_plus:


disqus: 
  enabled: true
  shortname: kakise
gravatar:
  email: 
