nav: NAV_PLACEHOLDER
projects_url: 'https://github.com/Kakise'
logo:
  enabled: true
  gravatar: false
  height: 50
  url: /images/logo.png
  width: 50
favicon:
  android:
    gravatar: false
    url: /images/android-icon-192x192.png
  apple:
    gravatar: false
    url: /images/apple-icon.png
  desktop:
    gravatar: false
    url: /images/favicon.ico
highlight: solarized-dark
page_width: '52'
rss: atom.xml
open_graph:
  twitter_id: Kakise_
disqus:
  enabled: true
  shortname: kakise
gravatar: {}